# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoTest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProtoTest.proto',
  package='ProtobufTest',
  serialized_pb='\n\x0fProtoTest.proto\x12\x0cProtobufTest\"\xa6\x02\n\x0bTestMessage\x12\x12\n\nclientName\x18\x01 \x02(\t\x12\x10\n\x08\x63lientId\x18\x02 \x02(\x05\x12\x19\n\x0b\x64\x65scription\x18\x03 \x01(\t:\x04NONE\x12\x37\n\x0cmessageitems\x18\x04 \x03(\x0b\x32!.ProtobufTest.TestMessage.MsgItem\x1ap\n\x07MsgItem\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x10\n\x08itemName\x18\x02 \x01(\t\x12\x11\n\titemValue\x18\x03 \x01(\x05\x12\x34\n\x08itemType\x18\x04 \x01(\x0e\x32\".ProtobufTest.TestMessage.ItemType\"+\n\x08ItemType\x12\t\n\x05TypeX\x10\x00\x12\t\n\x05TypeY\x10\x01\x12\t\n\x05TypeZ\x10\x02')



_TESTMESSAGE_ITEMTYPE = _descriptor.EnumDescriptor(
  name='ItemType',
  full_name='ProtobufTest.TestMessage.ItemType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TypeX', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeZ', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=285,
  serialized_end=328,
)


_TESTMESSAGE_MSGITEM = _descriptor.Descriptor(
  name='MsgItem',
  full_name='ProtobufTest.TestMessage.MsgItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ProtobufTest.TestMessage.MsgItem.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='itemName', full_name='ProtobufTest.TestMessage.MsgItem.itemName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='itemValue', full_name='ProtobufTest.TestMessage.MsgItem.itemValue', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='itemType', full_name='ProtobufTest.TestMessage.MsgItem.itemType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=171,
  serialized_end=283,
)

_TESTMESSAGE = _descriptor.Descriptor(
  name='TestMessage',
  full_name='ProtobufTest.TestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientName', full_name='ProtobufTest.TestMessage.clientName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientId', full_name='ProtobufTest.TestMessage.clientId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='ProtobufTest.TestMessage.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("NONE", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='messageitems', full_name='ProtobufTest.TestMessage.messageitems', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TESTMESSAGE_MSGITEM, ],
  enum_types=[
    _TESTMESSAGE_ITEMTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=328,
)

_TESTMESSAGE_MSGITEM.fields_by_name['itemType'].enum_type = _TESTMESSAGE_ITEMTYPE
_TESTMESSAGE_MSGITEM.containing_type = _TESTMESSAGE;
_TESTMESSAGE.fields_by_name['messageitems'].message_type = _TESTMESSAGE_MSGITEM
_TESTMESSAGE_ITEMTYPE.containing_type = _TESTMESSAGE;
DESCRIPTOR.message_types_by_name['TestMessage'] = _TESTMESSAGE

class TestMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class MsgItem(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TESTMESSAGE_MSGITEM

    # @@protoc_insertion_point(class_scope:ProtobufTest.TestMessage.MsgItem)
  DESCRIPTOR = _TESTMESSAGE

  # @@protoc_insertion_point(class_scope:ProtobufTest.TestMessage)


# @@protoc_insertion_point(module_scope)
